apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f mysql-docker-compose-v2.yml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: datasynthesisdb
  name: datasynthesisdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: datasynthesisdb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f mysql-docker-compose-v2.yml
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: datasynthesisdb
    spec:
      containers:
        - args:
            - --default-authentication-plugin=mysql_native_password
          env:
            - name: MYSQL_DATABASE
              value: datasynthesis
            - name: MYSQL_ROOT_PASSWORD
              value: letmein
          image: mysql:8.0.18
          name: datasynthesisdb
          ports:
            - containerPort: 3306
          resources: {}
      restartPolicy: Always
status: {}
