apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f mysql2-docker-compose.yml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: datasynthesisdb
  name: datasynthesisdb
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: datasynthesisdb
status:
  loadBalancer: {}
