apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f mysql2-docker-compose.yml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: quarkus
  name: quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: quarkus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f mysql2-docker-compose.yml
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: quarkus
    spec:
      containers:
        - args:
            - mvn
            - quarkus:dev
          env:
            - name: DATABASE_HOST
              value: datasynthesisdb
          image: maven
          name: quarkus
          ports:
            - containerPort: 5005
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: quarkus-claim0
            - mountPath: /root/.m2
              name: quarkus-claim1
          workingDir: /app
      restartPolicy: Always
      volumes:
        - name: quarkus-claim0
          persistentVolumeClaim:
            claimName: quarkus-claim0
        - name: quarkus-claim1
          persistentVolumeClaim:
            claimName: quarkus-claim1
status: {}
